name: magnetfruit_mysql_database_handler
version: 0.1.1
description: 'Avocadorm database handler for MySQL.'
author: Zyrthofar <zyrthofar@magnetfruit.com>
homepage: 'http://www.magnetfruit.com/databasehandler/'
dependencies:
  magnetfruit_database_handler: ">=0.1.2 <0.2.0"
  sqljocky: 0.11.0